// app/src/components/ChatProcessFold.tsx
import { useMemo } from 'react'
import ChatActivityGroup from '@/components/ChatActivityGroup'
import ChatMessageItem from '@/components/ChatMessageItem'
import {
  isThinkingOnlyAssistant,
  mergeProcessThinking,
  processFoldSummary,
  type ChatProcessFoldBlock,
  type ChatTurnBlock,
} from '@/lib/chatActivity'
import { useT } from '@/hooks/useUiLocale'
import type { SubagentTask } from '@/types'

export default function ChatProcessFold({
  protectedFolders,
  process,
  recoverableFailureId,
  recoveryContext,
  rewindableUserMessageId,
  rewindDisabled,
  kernel,
  activityOpen,
  activityOpenEntries,
  subagentTasks,
  onToggleGroup,
  onToggleEntry,
  onRespondApproval,
  onRetry,
  onEditUser,
  onRewindContext,
  onBranchAssistant,
}: {
  process: ChatProcessFoldBlock
  recoverableFailureId?: string | null
  recoveryContext?: 'ctf' | 'coding'
  rewindableUserMessageId?: string
  rewindDisabled?: boolean
  kernel?: 'pi' | 'dsh'
  /** 受限文件夹的**生效列表**（总开关关掉时为空）：折叠里的审批卡也用同一份事实。 */
  protectedFolders?: string[]
  activityOpen: (activityId: string) => boolean
  activityOpenEntries: (activityId: string) => ReadonlySet<string>
  subagentTasks?: readonly SubagentTask[]
  memoKey: string
  onToggleGroup?: (activityId: string, open: boolean) => void
  onToggleEntry?: (activityId: string, entryId: string, open: boolean) => void
  onRespondApproval?: (requestId: string, approved: boolean, scope?: 'once' | 'conversation', choice?: string) => void
  onRetry?: () => void
  onEditUser?: (messageId: string, content: string) => void
  onRewindContext?: () => void
  onBranchAssistant?: (messageId: string) => void
}) {
  const t = useT()
  const foldSummary = useMemo(() => processFoldSummary(process.blocks), [process.blocks])
  const foldedThinking = useMemo(() => mergeProcessThinking(process.blocks), [process.blocks])
  const visibleBlocks = useMemo(() => (
    process.blocks.filter((block): block is ChatTurnBlock => (
      block.kind === 'activity'
      || (block.kind === 'message' && !isThinkingOnlyAssistant(block.message))
    ))
  ), [process.blocks])

  return (
    <details className="agent-process mb-7">
      <summary className="agent-process__summary">
        <span>{t('过程', 'Process')}</span>
        {foldSummary ? <span className="agent-process__count">{foldSummary}</span> : null}
      </summary>
      <div className="agent-process__body">
        {foldedThinking ? (
          <ChatMessageItem
            protectedFolders={protectedFolders}
            message={foldedThinking}
            thinkingTotal
          />
        ) : null}
        {visibleBlocks.map(item => (
          item.kind === 'activity' ? (
            <ChatActivityGroup
              key={item.id}
              activity={item}
              open={activityOpen(item.id)}
              openEntryIds={activityOpenEntries(item.id)}
              subagentTasks={subagentTasks}
              revealCompleted
              onToggleGroup={open => onToggleGroup?.(item.id, open)}
              onToggleEntry={(entryId, open) => onToggleEntry?.(item.id, entryId, open)}
            />
          ) : (
            <ChatMessageItem
              protectedFolders={protectedFolders}
              key={item.id}
              message={item.message}
              recoverable={item.message.id === recoverableFailureId}
              recoveryContext={recoveryContext}
              canRewind={item.message.id === rewindableUserMessageId}
              rewindDisabled={rewindDisabled}
              kernel={kernel}
              onRespondApproval={(requestId, approved, scope, choice) => onRespondApproval?.(requestId, approved, scope, choice)}
              onRetry={onRetry}
              onEditUser={(messageId, content) => onEditUser?.(messageId, content)}
              onRewindContext={onRewindContext}
              onBranchAssistant={messageId => onBranchAssistant?.(messageId)}
            />
          )
        ))}
      </div>
    </details>
  )
}

// app/src/components-vue/ChatProcessFold.vue
<script setup lang="ts">
import { computed } from 'vue'
import ChatActivityGroup from '@/components-vue/ChatActivityGroup.vue'
import ChatMessageItem from '@/components-vue/ChatMessageItem.vue'
import {
  chatTranscriptBlockMemoRefs,
  isThinkingOnlyAssistant,
  mergeProcessThinking,
  processFoldSummary,
  type ChatProcessFoldBlock,
  type ChatTurnBlock,
} from '@/lib/chatActivity'
import { t } from '@/lib/uiLocale'
import type { SubagentTask } from '@/types'

const props = defineProps<{
  process: ChatProcessFoldBlock
  recoverableFailureId?: string | null
  recoveryContext?: 'ctf' | 'coding'
  rewindableUserMessageId?: string
  rewindDisabled?: boolean
  kernel?: 'pi' | 'dsh'
  activityOpen: (activityId: string) => boolean
  activityOpenEntries: (activityId: string) => ReadonlySet<string>
  subagentTasks?: readonly SubagentTask[]
  memoKey: string
}>()

const emit = defineEmits<{
  toggleGroup: [activityId: string, open: boolean]
  toggleEntry: [activityId: string, entryId: string, open: boolean]
  respondApproval: [requestId: string, approved: boolean, scope?: 'once' | 'conversation', choice?: string]
  retry: []
  editUser: [messageId: string, content: string]
  rewindContext: []
  branchAssistant: [messageId: string]
}>()

const foldSummary = computed(() => processFoldSummary(props.process.blocks))
const foldedThinking = computed(() => mergeProcessThinking(props.process.blocks))
const visibleBlocks = computed(() => (
  props.process.blocks.filter((block): block is ChatTurnBlock => (
    block.kind === 'activity'
    || (block.kind === 'message' && !isThinkingOnlyAssistant(block.message))
  ))
))

// Only the block the running turn touches changes its `blocks` array; the rest
// keep the same message references, so v-memo can skip their patch work.
function innerMemo(item: ChatTurnBlock): unknown[] {
  return chatTranscriptBlockMemoRefs(item, props.memoKey)
}
</script>

<template>
  <details class="agent-process mb-7">
    <summary class="agent-process__summary">
      <span>{{ t('过程', 'Process') }}</span>
      <span
        v-if="foldSummary"
        class="agent-process__count"
      >{{ foldSummary }}</span>
    </summary>
    <div class="agent-process__body">
      <ChatMessageItem
        v-if="foldedThinking"
        :message="foldedThinking"
        thinking-total
      />
      <template v-for="item in visibleBlocks" :key="item.id">
        <ChatActivityGroup
          v-if="item.kind === 'activity'"
          v-memo="innerMemo(item)"
          :activity="item"
          :open="activityOpen(item.id)"
          :open-entry-ids="activityOpenEntries(item.id)"
          :subagent-tasks="subagentTasks"
          reveal-completed
          @toggle-group="open => $emit('toggleGroup', item.id, open)"
          @toggle-entry="(entryId, open) => $emit('toggleEntry', item.id, entryId, open)"
        />
        <ChatMessageItem
          v-else
          v-memo="innerMemo(item)"
          :message="item.message"
          :recoverable="item.message.id === recoverableFailureId"
          :recovery-context="recoveryContext"
          :can-rewind="item.message.id === rewindableUserMessageId"
          :rewind-disabled="rewindDisabled"
          :kernel="kernel"
          @respond-approval="(requestId, approved, scope, choice) => $emit('respondApproval', requestId, approved, scope, choice)"
          @retry="$emit('retry')"
          @edit-user="(messageId, content) => $emit('editUser', messageId, content)"
          @rewind-context="$emit('rewindContext')"
          @branch-assistant="messageId => $emit('branchAssistant', messageId)"
        />
      </template>
    </div>
  </details>
</template>
