// app/src/components-vue/AppSidebar.vue
<script setup lang="ts">
import ContextSidebar from '@/components-vue/ContextSidebar.vue'
import { t } from '@/lib/uiLocale'
import type { ThemeMode } from '@/lib/themeMode'
import type { AppSection, CTFWorkspaceSection, WorkspaceSection } from '@/lib/workspaceNavigation'
import type { AccountStatus, Conversation, UpdateStatus } from '@/types'

defineProps<{
  activeSection: AppSection
  accountStatus: AccountStatus
  activeConversationId: string | null
  conversations: Conversation[]
  runningConversationIds?: string[]
  conversationActionError?: string
  ctfSection: CTFWorkspaceSection
  codingContextOpen?: boolean
  themeMode: ThemeMode
  updateStatus?: UpdateStatus | null
}>()

defineEmits<{
  new: []
  navigate: [value: WorkspaceSection]
  settings: []
  profile: []
  accountLogin: []
  accountLogout: []
  toggleTheme: []
  selectConversation: [id: string]
  deleteConversation: [id: string]
  deleteConversationPermanently: [id: string]
  newProjectSession: [workspacePath: string]
  renameConversation: [id: string, title: string]
  setPinned: [id: string, pinned: boolean]
  movePinned: [id: string, direction: -1 | 1]
  reorderPinned: [id: string, beforeId: string]
  navigateCtf: [value: CTFWorkspaceSection]
  openCodingContext: []
  collapseCodingContext: []
  downloadUpdate: []
  installUpdate: []
}>()
</script>

<template>
  <aside
    class="workspace-navigation-shell relative z-30 flex h-full min-h-0 shrink-0 text-sidebar-foreground"
    data-testid="stable-app-sidebar"
    :aria-label="t('工作区导航', 'Workspace navigation')"
  >
    <ContextSidebar
      :active-section="activeSection"
      :active-conversation-id="activeConversationId"
      :conversations="conversations"
      :running-conversation-ids="runningConversationIds"
      :action-error="conversationActionError"
      :ctf-section="ctfSection"
      :account-status="accountStatus"
      :theme-mode="themeMode"
      :update-status="updateStatus"
      :collapsed="!codingContextOpen"
      @new="$emit('new')"
      @collapse="$emit('collapseCodingContext')"
      @expand="$emit('openCodingContext')"
      @select-conversation="$emit('selectConversation', $event)"
      @delete-conversation="$emit('deleteConversation', $event)"
      @delete-conversation-permanently="$emit('deleteConversationPermanently', $event)"
      @new-project-session="$emit('newProjectSession', $event)"
      @rename-conversation="(id, title) => $emit('renameConversation', id, title)"
      @set-pinned="(id, pinned) => $emit('setPinned', id, pinned)"
      @move-pinned="(id, direction) => $emit('movePinned', id, direction)"
      @reorder-pinned="(id, beforeId) => $emit('reorderPinned', id, beforeId)"
      @navigate-ctf="$emit('navigateCtf', $event)"
      @navigate="$emit('navigate', $event)"
      @profile="$emit('profile')"
      @settings="$emit('settings')"
      @account-login="$emit('accountLogin')"
      @account-logout="$emit('accountLogout')"
      @toggle-theme="$emit('toggleTheme')"
      @download-update="$emit('downloadUpdate')"
      @install-update="$emit('installUpdate')"
    />
  </aside>
</template>

<style scoped>
.workspace-navigation-shell {
  border-right: 1px solid var(--border);
  background: var(--sidebar);
}
</style>

// app/src/components/AppSidebar.tsx
import ContextSidebar from '@/components/ContextSidebar'
import { useT } from '@/hooks/useUiLocale'
import type { ThemeMode } from '@/lib/themeMode'
import type { NormalizedSettingsCategory } from '@/lib/settingsNavigation'
import type { AppSection, CTFWorkspaceSection, WorkspaceSection } from '@/lib/workspaceNavigation'
import type { AccountStatus, Conversation, UpdateStatus } from '@/types'

export default function AppSidebar({
  activeSection,
  accountStatus,
  activeConversationId,
  conversations,
  runningConversationIds,
  conversationActionError,
  ctfSection,
  codingContextOpen,
  themeMode,
  updateStatus,
  onNew,
  onNavigate,
  onSettings,
  settingsCategory,
  onSelectSettingsCategory,
  onCloseSettings,
  onProfile,
  onAccountLogin,
  onAccountLogout,
  onToggleTheme,
  onSelectConversation,
  onDeleteConversation,
  onDeleteConversationPermanently,
  onNewProjectSession,
  onRenameConversation,
  onSetPinned,
  onMovePinned,
  onReorderPinned,
  onForkConversation,
  onNavigateCtf,
  onOpenCodingContext,
  onCollapseCodingContext,
  onApplyUpdate,
  onOpenCommandPanel,
}: {
  activeSection: AppSection
  accountStatus: AccountStatus
  activeConversationId: string | null
  conversations: Conversation[]
  runningConversationIds?: string[]
  conversationActionError?: string
  ctfSection: CTFWorkspaceSection
  codingContextOpen?: boolean
  themeMode: ThemeMode
  updateStatus?: UpdateStatus | null
  onNew?: () => void
  onNavigate?: (value: WorkspaceSection) => void
  onSettings?: () => void
  settingsCategory?: NormalizedSettingsCategory
  onSelectSettingsCategory?: (value: NormalizedSettingsCategory) => void
  onCloseSettings?: () => void
  onProfile?: () => void
  onAccountLogin?: () => void
  onAccountLogout?: () => void
  onToggleTheme?: () => void
  onSelectConversation?: (id: string) => void
  onDeleteConversation?: (id: string) => void
  onDeleteConversationPermanently?: (id: string) => void
  onNewProjectSession?: (workspacePath: string) => void
  onRenameConversation?: (id: string, title: string) => void
  onSetPinned?: (id: string, pinned: boolean) => void
  onMovePinned?: (id: string, direction: -1 | 1) => void
  onReorderPinned?: (id: string, beforeId: string) => void
  onForkConversation?: (id: string) => void
  onNavigateCtf?: (value: CTFWorkspaceSection) => void
  onOpenCodingContext?: () => void
  onCollapseCodingContext?: () => void
  onApplyUpdate?: () => void
  onOpenCommandPanel?: () => void
}) {
  const t = useT()
  return (
    <aside
      className="workspace-navigation-shell relative z-30 flex h-full min-h-0 shrink-0 text-sidebar-foreground"
      data-testid="stable-app-sidebar"
      aria-label={activeSection === 'settings' ? t('设置分类', 'Settings categories') : t('工作区导航', 'Workspace navigation')}
    >
      <ContextSidebar
        activeSection={activeSection}
        activeConversationId={activeConversationId}
        conversations={conversations}
        runningConversationIds={runningConversationIds}
        actionError={conversationActionError}
        ctfSection={ctfSection}
        accountStatus={accountStatus}
        themeMode={themeMode}
        updateStatus={updateStatus}
        collapsed={activeSection === 'settings' ? false : !codingContextOpen}
        settingsCategory={settingsCategory}
        onSelectSettingsCategory={onSelectSettingsCategory}
        onCloseSettings={onCloseSettings}
        onNew={onNew}
        onCollapse={onCollapseCodingContext}
        onExpand={onOpenCodingContext}
        onSelectConversation={onSelectConversation}
        onDeleteConversation={onDeleteConversation}
        onDeleteConversationPermanently={onDeleteConversationPermanently}
        onNewProjectSession={onNewProjectSession}
        onRenameConversation={onRenameConversation}
        onSetPinned={onSetPinned}
        onMovePinned={onMovePinned}
        onReorderPinned={onReorderPinned}
        onForkConversation={onForkConversation}
        onNavigateCtf={onNavigateCtf}
        onNavigate={onNavigate}
        onProfile={onProfile}
        onSettings={onSettings}
        onAccountLogin={onAccountLogin}
        onAccountLogout={onAccountLogout}
        onToggleTheme={onToggleTheme}
        onApplyUpdate={onApplyUpdate}
        onOpenCommandPanel={onOpenCommandPanel}
      />
      <style>{`
.workspace-navigation-shell {
  border-right: 1px solid var(--border);
  background: var(--sidebar);
}
`}</style>
    </aside>
  )
}
